### ISSUE TITLE
JetBrainsMono-NF@2.1.0: hash check failed

### ISSUE THREAD

**Issue by genemators** [matthewjberger/scoop-nerd-fonts#107] opened 2021-05-09 20:59 UTC
ERROR Hash check failed!
App:         nerd-fonts/JetBrainsMono-NF
URL:         https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    842013fa44b6896d4eb91635a81ef75244d78d7f61ff866c9dfd3315a67788cd
Actual:      fc3f7d3c12a303b8fd7b527179330f324be6458713c73ae3eae6dbbade7ce9b6

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/matthewjberger/scoop-nerd-fonts/issues/new?title=JetBrainsMono-NF%402.1.0%3a+hash+check+failed

**Comment by issaclin32** [comment] 2021-08-08 17:46
This issue is caused by that the developer of `JetBrainsMono-NF` has recently updated the file, but **Scoop** only checks every 3 hours. Therefore causing hash value to mismatch.

I am closing this issue because it has been already solved.

**Closed by issaclin32** 2021-08-08 17:46 UTC
